name: Build and Push Docker image to ECR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        env:
          IMAGE_NAME: patient     # change to "appointment" in the other repo
          IMAGE_TAG: ${{ github.sha }}
          ECR_ACCOUNT_ID: 548586340409
          AWS_REGION: us-east-1
        run: |
          ECR_URI=${ECR_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}
          echo "Building image ${IMAGE_NAME}"
          docker build -t ${IMAGE_NAME} .
          docker tag ${IMAGE_NAME}:latest ${ECR_URI}:${IMAGE_TAG}
          docker tag ${IMAGE_NAME}:latest ${ECR_URI}:latest
          docker push ${ECR_URI}:${IMAGE_TAG}
          docker push ${ECR_URI}:latest

      - name: Output image URIs (for logs)
        run: |
          echo "Patient image pushed to: ${ECR_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${IMAGE_NAME}:${{ github.sha }}"
          echo "and :latest"
